### PR TITLE
fixes #162 (Enhance Profile Sharing)

### LINKED ISSUE #162: Enhance profile sharing
**Is your feature request related to a problem? Please describe.**
When you choose to share your profile by pressing Share, you are taken to wavi.ng where you are shown the sharing options.

**Describe the solution you'd like**
It would be great if you could do the following after pressing share:
- Display a QR Code on screen that other people can scan to see your profile
- Be prompted to select an app to use in order to share the URL to your profile on wavi.ng  
- Be prompted to copy your profile URL

**Video of current behaviour**
https://user-images.githubusercontent.com/69275762/156783161-a0b77d96-2cc2-41a2-a78b-18a6cb2c8f86.mov

### PR DESCRIPTION
**Pull request by keyurgit45**
**- What I did**
     Earlier when we choose to share profile we were taken to the wavi.ng where we can see the sharing options. I added one screen for showing QR code to share the profile. also added a button named share via app which will prompt user to select any app for sharing the user's profile. Also in the platform's share dialog, we have a "copy to clipboard" option.

**- How I did it**
      I have used 2 packages, qr_flutter which takes data as a string and shows the QR code, share_plus - a Flutter plugin to share content from the Flutter app via the platform's share dialog. 

**- How to verify it**
      To verify the QR code, we have to scan one person's QR code from another person's wavi app. To verify the share via app button, we can share our profile using various apps shown in the share dialog.

**- Description for the changelog**
      Implemented QR code feature for sharing the user profile and added option to share via any app e.g. WhatsApp, Gmail, LinkedIn, etc.

### CODE REVIEW

**Comment by tinashe404** [comment]
This looks great! @sarika01 and @nitesh2599 please review?

**Comment by keyurgit45** [comment]
please review this PR too @yahu1031

**Comment by nitesh2599** [comment]
@tinashe404 I tested this PR today. 

When we scan the QR code of an atsign, the logged in atsign follows the QR code atsign.
Is this behaviour correct ?

**Comment by tinashe404** [comment]
@nitesh2599 @keyurgit45 It should only take the person to view the atsign. If the person wants to follow they can press the follow button.

**Comment by keyurgit45** [comment]
> @nitesh2599 @keyurgit45 It should only take the person to view the atsign. If the person wants to follow they can press the follow button.

I have implemented a method to show the QR code. QR scanner was already there,.

**Comment by nitesh2599** [comment]
@tinashe404 @keyurgit45 The QR scanner which is there, comes from the at_follows_flutter package, which follows the atsign when you scan a QR, it does not open the atsign's screen..

@tinashe404 what should we do here ?

**Comment by tinashe404** [comment]
@nitesh2599 We'll merge this and then it can be enhanced further at a later stage.

**Pull request merged**
