### PR TITLE
Updating Contributing.md:Fixing rendering issue

### LINKED ISSUE #166: Fix images in CONTRIBUTING.md
**Describe the bug**

The Contributing.md file is the first file any user visits when they are new to a repository. Having clean instructions and illustrations helps the user to easily follow along the md file. However all of the images linked aren't visible and while I click on the alt text it only leads to a 404 page. This should be fixed.

**Expected behavior**

All the images should appear properly.

**Screenshots**

### PR DESCRIPTION
**Pull request by Ash-KODES**
**- What I did**
Removed all the link of images which were missing and not rendering.
**- How I did it**

**- How to verify it**

**- Description for the changelog**

FIXES #166

### CODE REVIEW

**Comment by Ash-KODES** [comment]
Please Review @yahu1031

**Comment by nitesh2599** [comment]
Although this works good for a quick fix, but bringing the images over from https://github.com/atsign-foundation/at_app/tree/trunk/images, and making the code work would be the correct thing to do.

**Comment by Ash-KODES** [comment]
Closing this PR 
Reference #184

**Comment by yahu1031** [comment]
please try making changes in one PR. :)

**Pull request closed without merging**
