### PR TITLE
Fixes #148

### LINKED ISSUE #148: Make locations interactive
**Is your feature request related to a problem? Please describe.**
When you add a location to your page, It displays a map and a location title. When people are looking at your page in the app, they will see the map and title and they can expand the map to zoom and pan around.

**Describe the solution you'd like**
It would be good to be able to share this location, from the wavi app, with other apps like apple maps, google maps or to be able to open it in a browser so that you can use it to get directions to that location.

### PR DESCRIPTION
**Pull request by keyurgit45**
**- What I did**
      I used the url_launcher package to open google maps. When you add a location to your page, It displays a map and a location title. In that map tile, I have added a new icon below the fullscreen icon. So it will open google maps or apple maps according to respective coordinates.

**- How I did it**
     I have used the url_launcher package and written a function named openMaps to google maps or apple maps.
It will open the app according to the device.

**- How to verify it**
     To verify it, click on the location icon in the map tile (below the fullscreen icon). It will open the map in the respective app.

**- Description for the changelog**
      Added feature to open a location inside google maps or Apple maps.

### CODE REVIEW

**Comment by keyurgit45** [comment]
I don't have a physical IOS  device to test the functionality so if it doesn't work let me know.

**Comment by nitesh2599** [comment]
@keyurgit45 I tried this, it works on IOS (opens apple maps), but on android it doesn't.

Got this in the terminal for android:
`I/flutter (20352): Could not launch https://www.google.com/maps/search/?api=1&query=21.027165985728157,105.80263377877765`

**Comment by nitesh2599** [comment]
@keyurgit45 I tried on emulator.

**Comment by keyurgit45** [comment]
I have made the changes and tested it on the Android 9 and Android 12 emulators. @nitesh2599

**Comment by nitesh2599** [comment]
@keyurgit45 I tried this on android and it is working now. But please resolve the merge conflicts.

**Comment by keyurgit45** [comment]
Done! @nitesh2599

**Pull request merged**
