### PR TITLE
Fixes #164 (search bar autocorrect issue changes)

### LINKED ISSUE #164: Remove spaces and autocorrect functionality from the @sign search box
**Is your feature request related to a problem? Please describe.**
The atsign search box, which can be accessed by pressing the search icon on the top right corner of the main screen, is used to look up atsigns on the app. Atsigns can contain numbers, letters, emojis or an underscore ( _ ). They never contain spaces.

The search box currently makes it difficult to lookup atsign's like barbaras🐕🐕 and theamateuranteater because autocorrect puts spaces and punctuation into what is entered.

**Describe the solution you'd like**
It would be good if this search box did not attempt to correct user input. It would also be good be if it didn't accept the space character at all. 

**Video showing app behaviour**
https://user-images.githubusercontent.com/69275762/156782576-4935f712-5c2c-40d1-aaee-027e8e902812.mov

### PR DESCRIPTION
**Pull request by Ninad07**
- What I did
I disabled the search bar autocorrect and black space character input to solve the issue.

- How I did it
To disable autocorrect, Flutter's TextField Widget provides autocorrect option which I toggled to false, along with the enableSuggestions option. Also, this doesn't work if the device's keyboard's autocorrect is on. So I set the keyboardType as visiblePassword (TextInputType.visiblePassword). It prevents the autocorrect in both the cases.
To prevent blank space, I used the string replaceAll method and replaced white spaces to empty character in the onChanged function parameter of the textfield

- How to verify it
Type any user's atsign (for example barbaras). It previously autocorrected to Barbara's. Now it just displays barbaras, i.e. whatever we type. In case of blank spaces, the texfield won't accept the blank space in the input itself.

- Description for the changelog
Toggled Searchbar TextField autocorrect to false and set TextInputType to visiblePassword, for disabling autocorrect on the search bar.

### CODE REVIEW

**Review by nitesh2599 — COMMENTED** [review]
@Ninad07 I think that the `CustomInputField` still does not have any parameter, using which a widget can pass if it needs space or not. The same for autocorrect.

I think we should accept two more optional parameters, like autoCorrectNeeded and spacesAllowed. And the default value of them can be true and true respectively.

And we can pass them as false and false from the search widget respectively.

In the customInputField only replace the space if the spacesAllowed param is false.

**Comment by Ninad07** [comment]
Ok. Got the correct idea now. I'll make the changes

**Comment by Ninad07** [comment]
@nitesh2599 Can you see the changes?

**Review by nitesh2599 — COMMENTED** [review]
@Ninad07 The search bar autocorrect issue changes are working great.

But I also tried the email interactive change that you have put in, but it didn't do anything. (I tested it on an iOS simulator.)

**Comment by Ninad07** [comment]
@nitesh2599 I was working on multiple issues so I think you can see one of those commits, I have made a separate pull request for email interactive issue. https://github.com/atsign-foundation/at_wavi_app/pull/179/commits/c6ec683133bea9fd92262eb3b057ae20fa9da252. Please check it here

**Comment by nitesh2599** [comment]
@Ninad07 But this PR contains that commit, if I approve this one, then that commit will also be merged.

**Comment by Ninad07** [comment]
@nitesh2599 So shall I merge both these commits? The autocorrect and email issue I mean

**Pull request closed without merging**
