### PR TITLE
Fixes #164 (search bar autocorrect issue changes)

### LINKED ISSUE #164: Remove spaces and autocorrect functionality from the @sign search box
**Is your feature request related to a problem? Please describe.**
The atsign search box, which can be accessed by pressing the search icon on the top right corner of the main screen, is used to look up atsigns on the app. Atsigns can contain numbers, letters, emojis or an underscore ( _ ). They never contain spaces.

The search box currently makes it difficult to lookup atsign's like barbaras🐕🐕 and theamateuranteater because autocorrect puts spaces and punctuation into what is entered.

**Describe the solution you'd like**
It would be good if this search box did not attempt to correct user input. It would also be good be if it didn't accept the space character at all. 

**Video showing app behaviour**
https://user-images.githubusercontent.com/69275762/156782576-4935f712-5c2c-40d1-aaee-027e8e902812.mov

### PR DESCRIPTION
**Pull request by Ninad07**
What I did
I disabled the search bar autocorrect and black space character input to solve the issue.

How I did it
To disable autocorrect, Flutter's TextField Widget provides autocorrect option which I toggled to false, along with the enableSuggestions option. Also, this doesn't work if the device's keyboard's autocorrect is on. So I set the keyboardType as visiblePassword (TextInputType.visiblePassword). It prevents the autocorrect in both the cases.
To prevent blank space, I used the string replaceAll method and replaced white spaces to empty character in the onChanged function parameter of the textfield

How to verify it
Type any user's atsign (for example barbaras). It previously autocorrected to Barbara's. Now it just displays barbaras, i.e. whatever we type. In case of blank spaces, the texfield won't accept the blank space in the input itself.

Description for the changelog
Toggled Searchbar TextField autocorrect to false and set TextInputType to visiblePassword, for disabling autocorrect on the search bar.

### CODE REVIEW

**Comment by Ninad07** [comment]
@nitesh2599 Please check now

**Comment by tinashe404** [comment]
The search bar functionality looks good and works as expected. 
@nitesh2599 @sarika01 please could you do a code review on this PR. Thanks

**Comment by nitesh2599** [comment]
@Ninad07 Everything is working fine. 

But, one of the functionalities that we added to open any url link in webview has been removed in this PR.

In the `CustomCard` function the `onTap` functionality has been removed. 

Please check that.

**Comment by Ninad07** [comment]
@nitesh2599 Please check now

**Review by nitesh2599 — APPROVED** [review]
Changes working fine

**Comment by nitesh2599** [comment]
@yahu1031 We have a fix for #164

**Pull request merged**
